name: Latest blog post workflow
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Get Current Time
        id: current-time
        run: echo "::set-output name=time::$(date +'%Y-%m-%d %H:%M:%S')"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/arslanyousaf12"
          max_post_count: "3"
          template: "$newline$newline$counter. [$title]($url)"
          commit_message: "Updated README with latest blog posts - ${{ steps.current-time.outputs.time }}"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
