name: Latest blog post workflow
on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write # Add this line
    steps:
      - uses: actions/checkout@v2
      - name: Print Debug Info
        run: |
          echo "Feed URL: https://dev.to/feed/arslanyousaf12"
          curl -s https://dev.to/feed/arslanyousaf12
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/arslanyousaf12"
          max_post_count: "5"
          template: "- [$title]($url)"
          commit_message: "Updated README with latest blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          debug: true # Add this line for more debug info
